# This is a multiarch Dockerfile.  See https://docs.docker.com/desktop/multi-arch/
#
# To set up the first time:
#     docker buildx create --name multiarch --use
#
# To build:
#     docker buildx build --platform linux/amd64,linux/arm64 \
#       -f ./Dockerfile-postgresql -t zulip/zulip-postgresql:17 --push .

# Currently the PostgreSQL images do not support automatic upgrading of
# the on-disk data in volumes. So the base image cannot currently be upgraded
# without users needing a manual pgdump and restore.

# https://hub.docker.com/r/groonga/pgroonga/tags
ARG PGROONGA_VERSION=latest
ARG POSTGRESQL_VERSION=17
FROM groonga/pgroonga:${PGROONGA_VERSION}-alpine-${POSTGRESQL_VERSION}-slim

# Install hunspell dictionaries (en, de, bg), Zulip stop words, and run Zulip database init.
RUN apk add -U --no-cache hunspell-en hunspell-de hunspell-bg

# Link hunspell dictionaries for PostgreSQL tsearch (en_us, de_de, bg_bg)
RUN set -eux; \
    mkdir -p /usr/local/share/postgresql/tsearch_data; \
    ln -sf /usr/share/hunspell/en_US.dic /usr/local/share/postgresql/tsearch_data/en_us.dict; \
    ln -sf /usr/share/hunspell/en_US.aff /usr/local/share/postgresql/tsearch_data/en_us.affix; \
    ln -sf /usr/share/hunspell/de_DE.dic /usr/local/share/postgresql/tsearch_data/de_de.dict; \
    ln -sf /usr/share/hunspell/de_DE.aff /usr/local/share/postgresql/tsearch_data/de_de.affix; \
    ln -sf /usr/share/hunspell/bg_BG.dic /usr/local/share/postgresql/tsearch_data/bg_bg.dict; \
    ln -sf /usr/share/hunspell/bg_BG.aff /usr/local/share/postgresql/tsearch_data/bg_bg.affix

COPY puppet/zulip/files/postgresql/zulip_english.stop /usr/local/share/postgresql/tsearch_data/zulip_english.stop
COPY puppet/zulip/files/postgresql/zulip_german.stop /usr/local/share/postgresql/tsearch_data/german_english.stop
COPY puppet/zulip/files/postgresql/zulip_bulgarian.stop /usr/local/share/postgresql/tsearch_data/zulip_bulgarian.stop
COPY scripts/setup/create-db.sql /docker-entrypoint-initdb.d/zulip-create-db.sql
COPY scripts/setup/create-pgroonga.sql /docker-entrypoint-initdb.d/zulip-create-pgroonga.sql
